--- 
deploy: 
  docker: 
    - 
      image: "circleci/openjdk:8-jdk"
  steps: 
    - 
      attach_workspace: 
        at: "~/${wstest}"
    - 
      run: 
        command: "aws s3 sync ~/repo/ s3://${circleciwar}"
        name: Deploy
  working_directory: "~/${wstest}"
jobs: 
  build: 
    docker: 
      - 
        image: "circleci/openjdk:8-jdk"
version: 2
workflows: 
  build-and-deploy: 
    jobs: 
      - build
      - 
        deploy: 
          filters: 
            branches: 
              only: master
          requires: 
            - build
  environment: 
    JVM_OPTS: "-Xmx3200m"
    TERM: dumb
  steps: 
    - checkout
    - 
      restore_cache: 
        keys: 
          - "v1-dependencies-{{ checksum \"build.gradle\" }}"
          - v1-dependencies-
    - 
      run: "gradle dependencies"
    - 
      save_cache: 
        key: "v1-dependencies-{{ checksum \"build.gradle\" }}"
        paths: 
          - ~/.gradle
    - 
      run: "gradle test"
  version: 2
  working_directory: ~/repo
