--- 
jobs: 
  deploy-job: 
    docker: 
      - 
        image: circleci/openjdk:8-jdk
    steps: 
      - 
        run: 
          command: "aws s3 sync ${wstest} s3://s3-ap-southeast-2.amazonaws.com/circleciwar/--delete"
          name: "Deploy to S3 if tests pass and branch is Master"
    working_directory: /tmp/my-project
version: 2
workflows: 
  build-deploy: 
    jobs: 
      - build-job
      - 
        deploy-job: 
          filters: 
            branches: 
              only: master
          requires: 
            - build-job
  version: 2
