--- 
jobs: 
  build: 
    docker: 
      - 
        image: "circleci/openjdk:8-jdk"
    environment: 
      JVM_OPTS: "-Xmx3200m"
      TERM: dumb
    steps: 
      - checkout
      - 
        restore_cache: 
          keys: 
            - "v1-dependencies-{{ checksum \"build.gradle\" }}"
            - v1-dependencies-
      - 
        run: "gradle dependencies"
      - 
        save_cache: 
          key: "v1-dependencies-{{ checksum \"build.gradle\" }}"
          paths: 
            - ~/.gradle
      - 
        run: "gradle test"
    working_directory: ~/repo
  deploy: 
    dependencies: ~
    deployment: 
      prod: 
        branch: master
        commands: 
          - "aws s3 sync /home/ubuntu/wstest s3://circleciwar --delete"
    machine: 
      enabled: true
    override: 
      - "sudo pip install awscli"
    working_directory: ~/repo
version: 2
