--- 
jobs: 
  build: 
    docker: 
      - 
        image: "circleci/openjdk:8-jdk"
    environment: 
      JVM_OPTS: "-Xmx3200m"
      TERM: dumb
    steps: 
      - checkout
      - 
        restore_cache: 
          keys: 
            - "v1-dependencies-{{ checksum \"build.gradle\" }}"
            - v1-dependencies-
      - 
        run: "gradle dependencies"
      - 
        save_cache: 
          key: "v1-dependencies-{{ checksum \"build.gradle\" }}"
          paths: 
            - ~/.gradle
      - 
        run: "gradle test"
      - 
        run: "gradle build"
      - 
        run: "ls /tmp/app/"
      - 
        run: "ls /tmp/"
      - 
        run: "ls -as"
      - 
        run: 
          command: "sudo apt-get -y -qq install awscli"
          name: "Install awscli"
      - 
        run: 
          command: "aws configure list"
          name: "show credentials"
      - 
        run: 
          command: "ssh -v -i /home/ubuntu/.ssh/StackPem  -f -N -L 1205:10.0.5.31:22 ubuntu@52.63.148.245"
      - 
        run: 
          command: "scp -v -i /home/ubuntu/.ssh/StackPem -P 1205 -r /tmp/app/build/libs/* ubuntu@localhost:/tmp/circleci_files"
    working_directory: /tmp/app
version: 2

