--- 
jobs: 
  build-job: 
    docker: 
      - 
        image: "circleci/openjdk:8-jdk"
    steps: 
      - checkout
      - 
        restore_cache: 
          keys: 
            - "v1-dependencies-{{ checksum \"build.gradle\" }}"
            - v1-dependencies-
      - 
        run: "gradle dependencies"
      - 
        save_cache: 
          key: "v1-dependencies-{{ checksum \"build.gradle\" }}"
          paths: 
            - ~/.gradle
      - 
        run: "gradle test"
      - 
        run: "gradle war"
      - 
        run: "ls /tmp/app/build/libs"
      - 
        run: "ls /tmp/"
      - 
        run: "ls /"
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - .
    working_directory: /tmp/app
  deploy-job: 
    docker: 
      - 
        image: "circleci/openjdk:8-jdk"
    steps: 
      - 
        run: 
          command: "sudo apt-get -y -qq install awscli"
          #command: "sudo pip install awscli"
          name: "Install awscli"
      - 
        run: 
          command: "aws configure list"
          name: "show credentials"
      - 
        run: 
          command: "aws s3 sync /tmp/app/ s3://circleciwar --delete"
          name: "Deploy to S3 circleciwar bucket"
    working_directory: /tmp/app
version: 2
workflows: 
  build-deploy: 
    jobs: 
      - build-job
      - 
        deploy-job: 
          filters: 
            branches: 
              only: master
          requires: 
            - build-job
  version: 2
